----SCENE 25----

HEAD KNIGHT:  Nee! Nee! Nee! Nee!

ARTHUR:  Who are you?

HEAD KNIGHT:  We are the Knights Who Say... Nee!

ARTHUR:  No!  Not the Knights Who Say Nee!

HEAD KNIGHT:  The same!

BEDEMIR:  Who are they?

HEAD KNIGHT:  We are the keepers of the sacred words:  Nee, Pen, and Nee-wom!

RANDOM:  Nee-wom!

ARTHUR:  Those who hear them seldom live to tell the tale!

HEAD KNIGHT:  The Knights Who Say Nee demand a sacrifice!

ARTHUR:  Knights of Nee, we are but simple travellers who seek the enchanter who lives beyond these woods.

HEAD KNIGHT:  Nee!  Nee!  Nee!  Nee!

ARTHUR and PARTY:  Oh, ow!

HEAD KNIGHT:  We shall say 'nee' again to you if you do not appease us.

ARTHUR:  Well, what is it you want?

HEAD KNIGHT:  We want... a shrubbery!

[dramatic chord]

ARTHUR:  A what?

HEAD KNIGHT:  Nee!  Nee!

ARTHUR and PARTY:  Oh, ow!

ARTHUR:  Please, please!  No more!  We shall find a shrubbery.

HEAD KNIGHT:  You must return here with a shrubbery or else you will never pass through this wood alive!

ARTHUR:  O Knights of Nee, you are just and fair, and we will return with a shrubbery.

HEAD KNIGHT:  One that looks nice.

ARTHUR:  Of course.

HEAD KNIGHT:  And not too expensive.

ARTHUR:  Yes.

HEAD KNIGHTS:  Now... go!




----SCENE 31----

ARTHUR:  O, Knights of Nee, we have brought you your shrubbery.  May we go now?

HEAD KNIGHT:  It is a good shrubbery.  I like the laurels particularly. But there is one small problem.

ARTHUR:  What is that?

HEAD KNIGHT:  We are now... no longer the Knights Who Say Nee.

RANDOM:  Nee!

HEAD KNIGHT:  Shh shh.  We are now the Knights Who Say Ecky-ecky-ecky-ecky-pikang-zoom-boing-mumble-mumble.

RANDOM:  Nee!

HEAD KNIGHT:  Therefore, we must give you a test.

ARTHUR:  What is this test, O Knights of-- Knights Who 'Til Recently Said Nee?

HEAD KNIGHT:  Firstly, you must find... another shrubbery!

[dramatic chord]

ARTHUR:  Not another shrubbery!

HEAD KNIGHT:  Then, when you have found the shrubbery, you must place it here beside this shrubbery, only slightly higher so you get a two-level effect with a little path running down the middle.

RANDOM:  A path!  A path!  Nee!

HEAD KNIGHT:  Then, when you have found the shrubbery, you must cut down the mightiest tree in the forest... with... a herring!

[dramatic chord]

ARTHUR:  We shall do no such thing!

HEAD KNIGHT:  Oh, please!

ARTHUR:  Cut down a tree with a herring?  It can't be done.

KNIGHTS:  Aaaaugh!  Aaaugh!

HEAD KNIGHT:  Don't say that word.

ARTHUR:  What word?

HEAD KNIGHT:  I cannot tell, suffice to say is one of the words the Knights of Nee cannot hear.

ARTHUR:  How can we not say the word if you don't tell us what it is?

KNIGHTS:  Aaaaugh!  Aaaugh!

ARTHUR:  What, 'is'?
   
HEAD KNIGHT:  No, not 'is' -- we couldn't get vary far in life not saying 'is'.

BEDEMIR:  My liege, it's Sir Robin!

MINSTREL (singing):  
Packing it in and packing it up
And sneaking away and buggering up
And chickening out and pissing about
Yes, bravely he is throwing in the sponge

ARTHUR:  Oh, Robin!

ROBIN:  My liege!  It's good to see you!

KNIGHTS:  Aaaaugh!

HEAD KNIGHT:  He said the word!

ARTHUR:  Surely you've not given up your quest for the Holy Grail?

MINSTREL (singing):  He is sneaking away and buggering up--

ROBIN:  Shut up!  No, no no-- far from it.

HEAD KNIGHT:  He said the word again!

ROBIN:  I was looking for it.
   
KNIGHTS:  Aaaaugh!

ROBIN:  Uh, here, here in this forest.

ARTHUR:  No, it is far from--
   
KNIGHTS:  Aaaaugh!

HEAD KNIGHT:  Aaaaugh!  Stop saying the word!

ARTHUR:  Oh, stop it!

KNIGHTS:  Aaaaugh!
   
HEAD KNIGHT:  Oh!  He said it again!

ARTHUR:  Patsy!

HEAD KNIGHT:  Aaugh!  I said it!  I said it!  Ooh!  I said it again!

KNIGHTS:  Aaaaugh!