/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.CANBuses;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LightStrip extends SubsystemBase {
    private final CANdle m_candle = new CANdle(4, CANBuses.intake);
    

    private final SolidColor[] m_colors = new SolidColor[] {
        new SolidColor(0, 7).withColor(new RGBWColor(0, 255, 255, 0)),
        new SolidColor(0, 7).withColor(new RGBWColor(255, 0, 255, 0)),
    };

    public LightStrip() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
        });
    }
}
