/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.CANBuses;

import java.util.function.DoubleSupplier;

import com.ctre.phoenix6.configs.CANdleConfiguration;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import com.ctre.phoenix6.signals.StripTypeValue;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LightStrip extends SubsystemBase {
    private final CANdle rightCANdle = new CANdle(4, CANBuses.shooter);
    private final CANdle leftCANdle = new CANdle(5, CANBuses.shooter);
    private DoubleSupplier confidenceSupplier;

    public LightStrip(DoubleSupplier confidenceSupplier) {
        this.confidenceSupplier = confidenceSupplier;
        CANdleConfiguration configs = new CANdleConfiguration();
        configs.LED.StripType = StripTypeValue.GRB;
        rightCANdle.getConfigurator().apply(configs);
        leftCANdle.getConfigurator().apply(configs);
    }

    @Override
    public void periodic() {
        super.periodic();

        var confidence = confidenceSupplier.getAsDouble(); // 0 - 100

        var green = (int)(255 * (Math.pow(confidence / 100, 6)));
        var red = 255 - green;

        setColors(new SolidColor(0, 7)
            .withColor(new RGBWColor(red, green, 0)));
    }

    private void setColors(SolidColor color) {
        rightCANdle.setControl(color);
        leftCANdle.setControl(color);
    }
}