/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.CANBuses;

import com.ctre.phoenix6.configs.CANdleConfiguration;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.RGBWColor;
import com.ctre.phoenix6.signals.StripTypeValue;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LightStrip extends SubsystemBase {
    private final CANdle rightCANdle = new CANdle(4, CANBuses.shooter);
    private final CANdle leftCANdle = new CANdle(5, CANBuses.shooter);

    private boolean isOn = true;

    private final SolidColor[] color1 = new SolidColor[] {
        new SolidColor(0, 8).withColor(new RGBWColor(24, 72, 255, 0)),
    };
    private final SolidColor[] color2 = new SolidColor[] {
        new SolidColor(0, 8).withColor(new RGBWColor(255, 0, 0, 0)),
    };

    public LightStrip() {
        CANdleConfiguration configs = new CANdleConfiguration();
        configs.LED.StripType = StripTypeValue.GRB;
        rightCANdle.getConfigurator().apply(configs);
        if(DriverStation.getAlliance().isPresent()) {
            if(DriverStation.getAlliance().get() == Alliance.Blue) {
                toBlue();
            } else {
                toRed();
            }
        }
        else {
            toGreen();
        }
    }
  
    private void setColors(SolidColor color) {
        rightCANdle.setControl(color);
        leftCANdle.setControl(color);
    }
    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : color1) {
                leftCANdle.setControl(solidColor);
            }    

            for (var solidColor : color2) {
                rightCANdle.setControl(solidColor);
            }
        });
    };

    public void toRed() {
        SolidColor red = new SolidColor(0, 135).withColor(new RGBWColor(255, 0, 0));
        setColors(red);
        SmartDashboard.putString("Lights/color", "red");
    }

    public void toOrange() {
        SolidColor orange = new SolidColor(0, 135).withColor(new RGBWColor(255, 150, 0));
        setColors(orange);
        SmartDashboard.putString("Lights/color", "orange");
    }

    public void toGreen() {
        SolidColor green = new SolidColor(0, 135).withColor(new RGBWColor(0, 255, 0));
        setColors(green);
        SmartDashboard.putString("Lights/color", "green");
    }

    public void toBlue() {
        SolidColor blue = new SolidColor(0, 135).withColor(new RGBWColor(0, 0, 255));
        setColors(blue);
        SmartDashboard.putString("Lights/color", "blue");
    }

    public void switchColor() {
        if(isOn) {
            toBlue();
            isOn = false;
        } else {
            toRed();
            isOn = true;
        }
    }
}